#+title: active record pattern

Colloquially referred to as an [[file:20210326111212-orm.org][ORM]]. It's useful to know this [[file:20210326111346-precising_term_technology.org][precising term (technology)]] to gain access to (or "unlock") research and discussion surronding the topic.

While the discourse around these [[file:20210326111346-precising_term_technology.org][precising terms]] can be short on or even devoid of first-hand experience or diverse viewpoints. So [[file:20210326111431-real_world_programmers.org][real world programmers]] are right to have skepticism, but many [[file:20210326114704-throw_the_baby_out_with_the_bathwater.org][throw the baby out with the bathwater]] and miss out on information that could help reach the intended goal.

#+begin_quote
In software engineering, the active record pattern is considered an architectural pattern by some people and as an anti-pattern by some others recently.[1][2] It is found in software that stores in-memory object data in relational databases. It was named by Martin Fowler in his 2003 book Patterns of Enterprise Application Architecture.[3] The interface of an object conforming to this pattern would include functions such as Insert, Update, and Delete, plus properties that correspond more or less directly to the columns in the underlying database table.

The active record pattern is an approach to accessing data in a database. A database table or view is wrapped into a class. Thus, an object instance is tied to a single row in the table. After creation of an object, a new row is added to the table upon save. Any object loaded gets its information from the database. When an object is updated, the corresponding row in the table is also updated. The wrapper class implements accessor methods or properties for each column in the table or view.
#+end_quote
