#+title: Remmina exwm configuration

* Using [[file:20210502164308-remmina.org][Remmina]] and [[file:20210502164243-rdp.org][RDP]]/[[file:20210502164906-xrdp.org][xrdp]] is quite nice, however just setting my default window manager like:

#+begin_src nix
  services.xrdp = {
    enable = true;
    defaultWindowManager = "exwm";
  }
#+end_src

Doesn't seem to pick up my exwm session I define:

#+begin_src nix
services.xserver = {
    enable = true;
    xkbOptions = "ctrl:nocaps";
    desktopManager = {
      xfce.enable = true;
    };
    windowManager.session = lib.singleton {
      name = "exwm";
      start = ''
        export EDITOR='emacsclient -t -a emacs'
        $EDITOR
      '';
    };
    libinput.enable = true;
  }
#+end_src

One problem is that =ctrl:nocaps= doesn't actually take effect in the rdp host.

* It seems that startwm.sh generated by the xrdp nix expression isn't talking about ones sessions, but instead about runnable binaries?

https://github.com/NixOS/nixpkgs/blob/8284fc30c84ea47e63209d1a892aca1dfcd6bdf3/nixos/modules/services/networking/xrdp.nix#L15

* What xsession is loaded?

** What is the effect of sourcing =/etc/profile=?

*** I'd guess that my =setxkbmap= call should be there?

* it looks like this might be why things like =xfce4-session= exist
#+begin_src nix
    defaultWindowManager = "xfce4-session";
#+end_src

https://github.com/federatedcloud/COBRAContainers/blob/d98f5053566120fd10669f82eee32922425203e5/VMconfig/configuration.nix#L119

** or maybe not.. that's just for xfce4's own session management

* Does xrdp not respect x11 settings?

* I think I want to get xrdp to start the same .xinitrc xserver does for xfce4

** do I need to amke sure my session has a =.xinitrc= like the xfce4 desktop sesion does

https://github.com/NixOS/nixpkgs/blob/8284fc30c84ea47e63209d1a892aca1dfcd6bdf3/nixos/modules/services/x11/desktop-managers/xfce.nix

#+begin_src nix
    services.xserver.desktopManager.session = [{
      name = "xfce";
      desktopNames = [ "XFCE" ];
      bgSupport = true;
      start = ''
        ${pkgs.runtimeShell} ${pkgs.xfce.xfce4-session.xinitrc} &
        waitPID=$!
      '';
    }];
#+end_src

** what do other windowManager.session's do?

*** hmm looking at dwm's I realized I don't actually enable the session I create

* related

** https://github.com/NixOS/nixpkgs/issues/57717

** https://askubuntu.com/questions/216230/remote-desktop-to-ubuntu-has-wrong-keyboard-mapping
